apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer-service
  ports:
    - protocol: "TCP"
      port: 8086
      targetPort: 8086
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
spec:
  selector:
    matchLabels:
      app: producer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
        - name: producer-service
          image: smeefie/producerprototype:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
#          env:
#            - name: kafka-service
#              value: "kafka-service"